# Programs to be run before every commit, to ensure code quality

repos:
  # Use the Uncompromising Code Formatter on code and code blocks in documentation
  - repo: https://github.com/ambv/black.git
    rev: 20.8b1
    hooks:
      - id: black
        name: Run black format code

  # Check `noqa` statements
  - repo: https://github.com/pre-commit/pygrep-hooks.git
    rev: v1.7.1
    hooks:
      - id: python-use-type-annotations
        name: python-check-blanket-noqa

  # Various minor formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
      - id: check-yaml
        name: Check YAML files
      - id: trailing-whitespace
        name: Check trailing whitespace
        exclude: (?x)^(doc/analysis.org)$
      - id: end-of-file-fixer
        name: Check files end in single new line
      - id: mixed-line-ending
        name: Check for uniform line endings
      - id: check-executables-have-shebangs
        name: Check executables have shebangs

  # Hooks to check these hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: Check hooks apply
