#!/bin/env python3
#PBS -q QUEUE
#PBS -P PROJECT
#PBS -l ncpus=NUMCPUS
#PBS -l walltime=TIME
#PBS -l mem=MEMORYGB
#PBS -l jobfs=JOBSTORAGEGB
#PBS -lstorage=LINKSTORAGE
#PBS -j oe
#PBS -l wd
#PBS -o OUTPUTDIR
#PBS -l ngpus=NUMGPUS
import os
import socket
import subprocess

from colarunscripts.newmanageJob import main
from colarunscripts.utilities import GetJobID

print(f"Running on host {socket.gethostname()}")
subprocess.run('module list',shell=True)
subprocess.run(["ulimit","-s","unlimited"])    #Unlimiting stacksize (VITAL)
subprocess.run(["ulimit","-c","0"])            #0 size available for coredumps
subprocess.run(["ulimit","-a"])                #Showing those details

environment = os.environ
jobID = GetJobID(environment)

originalParametersFile = "ORIGINALPARAMETERSFILE"
newParametersFile = "PARAMETERSDIR"+f"{jobID}_parameters.yml"
kappa = KAPPA
nthConfig = NTHCONFIG
numJobs = NUMJOBS
testing = "TESTING"

main(originalParametersFile,newParametersFile,kappa,nthConfig,numJobs,testing)
