#!/bin/bash
#PBS -q QUEUE
#PBS -P PROJECT
#PBS -l ncpus=NUMCPUS
#PBS -l walltime=TIME
#PBS -l mem=MEMORYGB
#PBS -l jobfs=JOBSTORAGEGB
#PBS -lstorage=LINKSTORAGE
#PBS -j oe
#PBS -l wd
#PBS -o OUTPUTDIR
#PBS -l ngpus=NUMGPUS

echo Running on host `hostname`
source /home/566/tk9944/gadi_modules.sh
ulimit -s unlimited
ulimit -c 0
ulimit -a

python3 /home/566/tk9944/PhD/runscripts/colarunscripts/newmanageJob.py PARAMETERSDIR KAPPA NTHCONFIG NUMJOBS NCON TESTING
