#!/bin/bash
#SBATCH --partition=QUEUE
#SBATCH --nodes=NODES
#SBATCH --ntasks=NUMCPUS
#SBATCH --time=TIME
#SBATCH --mem=MEMORYGB
#SBATCH --output=OUTPUTDIR
#SBATCH --gres=gpu:NUMGPUS

echo Running on host `hostname`
echo Time is `date`
echo

#Phoenix currently having an issue with the hpcfs file system and linking to
#the home directory. This fixes the issue.
export HOME=/hpcfs/users/$USER

source /home/a1724542/New_phoenix_modules.sh
ulimit -s unlimited
ulimit -c 0
ulimit -a

python /home/a1724542/PhD/runscripts/colarunscripts/manageJob.py PARAMETERSDIR KAPPA NTHCONFIG NUMJOBS NCON TESTING
