#!/bin/bash
#SBATCH --partition=QUEUE
#SBATCH --nodes=NODES
#SBATCH --ntasks=NUMCPUS
#SBATCH --time=TIME
#SBATCH --mem=MEMORYGB
#SBATCH --output=OUTPUTDIR
#SBATCH --gres=gpu:NUMGPUS
#SBATCH --account=PROJECT

echo Running on host `hostname`
echo Time is `date`
echo
source /home/566/tk9944/gadi_modules.sh
ulimit -s unlimited
ulimit -c 0
ulimit -a

python3 /home/566/tk9944/PhD/runscripts/colarunscripts/manageJob.py PARAMETERSDIR KAPPA NTHCONFIG NUMJOBS NCON TESTING
